server:
  port: 80
  servlet:    context-path: /
spring:  datasource:    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .html
mybatis-plus:
  type-aliases-package: com.njw.vip.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:  level:    com.njw.vip: debug

             